### ISSUE TITLE
Diablo (USA) Infinite Loading Loop w/o Patch

### ISSUE THREAD

**Issue by Fidofidder** [alex-free/psx80mp#1]
I believe Diablo may also require patching to run properly on PS2. Inserting the unpatched disc into my SCPH-39001 causes the disc to endlessly spool up during the game's initial load sequence without ever finishing. However, the patched disc loads right away despite the FMVs still stuttering quite a bit which isn't something I've observed in my other burns or PS1 games. Even ejecting the unpatched disc during its load loop and then inserting the patched disc in its stead will cause the load to complete. I went ahead and disassembled and cleaned the laser's lens with IPA, but all three of the different burns I made with an unpatched disc still refuse to load.

**Comment by alex-free** [comment]
> I believe Diablo may also require patching to run properly on PS2. Inserting the unpatched disc into my SCPH-39001 causes the disc to endlessly spool up during the game's initial load sequence without ever finishing. However, the patched disc loads right away despite the FMVs still stuttering quite a bit which isn't something I've observed in my other burns or PS1 games. Even ejecting the unpatched disc during its load loop and then inserting the patched disc in its stead will cause the load to complete. I went ahead and disassembled and cleaned the laser's lens with IPA, but all three of the different burns I made with an unpatched disc still refuse to load.

I'll have to check it out, but very well could be another game that is problematic when burned to 80 minute CD-Rs.

Are you re-lubricating the drive when as well? That can help the stuttering. Besides that the laser might be on its way out.

Thanks for the report.

**Comment by Fidofidder** [comment]
No, I haven't lubricated the drive and its rails yet. It is possible it may just be this particular drive/laser going, and the dummy data is somehow allowing it to barely function with the burn.

**Comment by alex-free** [comment]
Added Diablo (USA) to  the 80 minute sensitive games list in the readme. Thanks for the report.
